label variable igae_gral "Índice general"
label variable igae_agri "Agricultura, pecuaria, silvicultura, caza y pesca"
label variable igae_petg "Petróleo crudo y gas natural"
label variable igae_mine "Minerales metálicos y no metálicos"
label variable igae_indm "Industria manufacturera"
label variable igae_elec "Electricidad, gas y agua"
label variable igae_cons "Construcción"
label variable igae_comr "Comercio"
label variable igae_tran "Transporte y almacenamiento"
label variable igae_comu "Comunicaciones"
label variable igae_fina "Establecimientos financieros, seguros, bienes inmuebles"
label variable igae_admp "Servicios de la administración pública"
label variable igae_otros "Otros servicios (1)"
